[package]
name = "secretary"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
poise = "0.5.2"
log = "0.4.17"
env_logger = "0.10.0"
chrono = "0.4.23"
rand = "0.8.5"